name: telegram_music_player
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  audio_video_progress_bar: ^2.0.1
  rxdart: ^0.27.7
  id3tag: ^0.2.0
  on_audio_query: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
